const { Router } = require('express')
const router = new Router()
const stuffController = require('../controllers/stuffController')
const authStuffMiddleware = require('../middleware/authStuffMiddleware')
const tarifRouter = require('./tarifRouter')
const attractionRouter = require('./attractionRouter')
const parkRouter = require('./parkRouter')
const greenZoneRouter = require('./greenZoneRouter')

router.post('/registration', stuffController.registration)
router.post('/login', stuffController.login)
router.get('/auth', authStuffMiddleware, stuffController.check)
router.use('/park', parkRouter)
router.get('/getPark', authStuffMiddleware, stuffController.getGreenZone)
router.use('/attraction', attractionRouter)
router.get('/getAttraction', authStuffMiddleware, stuffController.getAttraction)
router.use('/tarif', tarifRouter)
router.get('/getTarif', authStuffMiddleware, stuffController.getTarif)
router.use('/greenZone', greenZoneRouter)

module.exports = router
